@echo off
echo Installing dependencies...
call npm install
echo Building TypeScript...
call npm run build
echo Packaging with pkg...
npx pkg dist/index.js --targets node18-win-x64 --output ../dist/auto-resume-server.exe
echo Done! Executable: dist/auto-resume-server.exe
pause
